import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: "http",
        hostname: "localhost",
        port: "3000",
        pathname: "/**",
      },
      {
        protocol: 'https',
        hostname: '**',
        pathname: '/**',
      },

    ],
  },

  async redirects() {
    return [
      { source: "/privacy-policy", destination: "/policy", statusCode: 301 },
      { source: "/uslugi", destination: "/services", statusCode: 301 },
      { source: "/organizaciya-provedeniye", destination: "/services/events", statusCode: 301 },
      { source: "/chastnye_meropriyatiya", destination: "/services/events", statusCode: 301 },
      { source: "/corporate", destination: "/services/events/dlia-korporativa", statusCode: 301 },
      { source: "/vypusknoj-vecher", destination: "/services/events", statusCode: 301 },
      { source: "/detskie_prazdniki", destination: "/services/events", statusCode: 301 },
      { source: "/koncertnye-meropriyatiya", destination: "/services/events/dlia-koncerta", statusCode: 301 },
      { source: "/biznes-meropriyatiya", destination: "/services/events/dlia-korporativa", statusCode: 301 },
      { source: "/oformlenie-prazdnikov", destination: "/", statusCode: 301 },
      { source: "/vozdushnye_shary", destination: "/services/special-effects/sbros-sarov", statusCode: 301 },
      { source: "/dekor-tkanyami", destination: "/services/special-effects", statusCode: 301 },
      { source: "/ukrashenie_mashin", destination: "/", statusCode: 301 },
      { source: "/event-kompaniya", destination: "/", statusCode: 301 },
      { source: "/veduwie", destination: "/", statusCode: 301 },
      { source: "/shou-programmy", destination: "/", statusCode: 301 },
      { source: "/clown", destination: "/", statusCode: 301 },
      { source: "/fotosemka", destination: "/", statusCode: 301 },
      { source: "/videosemka", destination: "/", statusCode: 301 },
      { source: "/fejerverki-salyuty-pirotehnika", destination: "/services/special-effects", statusCode: 301 },
      { source: "/vyezdnoe-obsluzhivanie", destination: "/", statusCode: 301 },
      { source: "/vyezdnaya-kalyannaya", destination: "/", statusCode: 301 },
      { source: "/tancuyuwie-golovy", destination: "/", statusCode: 301 },
      { source: "/tamada", destination: "/", statusCode: 301 },
      { source: "/vostochnye_tancy", destination: "/", statusCode: 301 },
      { source: "/cygane", destination: "/", statusCode: 301 },
      { source: "/pushki-so2", destination: "/services/special-effects/kriopuska", statusCode: 301 },
      { source: "/pushki-konfetti", destination: "/services/special-effects/konfetti", statusCode: 301 },
      { source: "/ded-moroz-i-snegurochka", destination: "/", statusCode: 301 },
      { source: "/prokat-stolbikov-s-kanatami-krasnoj-dorozhki", destination: "/services/special-effects/stolbiki-noznicy", statusCode: 301 },
      { source: "/prazdnichnye-tovary", destination: "/", statusCode: 301 },
      { source: "/lenty-pocheta-lenty-vypusknikov", destination: "/", statusCode: 301 },
      { source: "/pnevmohlopushki-nebesnye-fonariki", destination: "/", statusCode: 301 },
      { source: "/ballony", destination: "/services/special-effects/sbros-sarov", statusCode: 301 },
      { source: "/gelievye-shary", destination: "/services/special-effects/sbros-sarov", statusCode: 301 },
      { source: "/novyj-god", destination: "/", statusCode: 301 },
      { source: "/partnery-kompanii-avantazh", destination: "/", statusCode: 301 },
      { source: "/klienty", destination: "/", statusCode: 301 },
      { source: "/akcii", destination: "/", statusCode: 301 },
      { source: "/articles", destination: "/", statusCode: 301 },
      { source: "/nevestam-polozheno-imet-buket-muftu", destination: "/", statusCode: 301 },
      { source: "/bukety-iz-strany-utrennej-svezhesti", destination: "/", statusCode: 301 },
      { source: "/svadba-v-venecii", destination: "/", statusCode: 301 },
      { source: "/vozdushnomu-shariku-ispolnilos-155-let", destination: "/", statusCode: 301 },
      { source: "/fata-na-snegu", destination: "/", statusCode: 301 },
      { source: "/kak-otmetit-den-goroda", destination: "/", statusCode: 301 },
      { source: "/klouny-animatory", destination: "/", statusCode: 301 },
      { source: "/oformlenie-prazdnichnyh-sobytij", destination: "/services/events", statusCode: 301 },
      { source: "/kak-podgotovitsya-k-novomu-godu", destination: "/services/events", statusCode: 301 },
      { source: "/stoit-li-zvat-deda-moroza-na-novyj-god", destination: "/", statusCode: 301 },
      { source: "/kak-prazduyut-novyj-god-v-raznyh-stranah-mira", destination: "/", statusCode: 301 },
      { source: "/kak-ustroit-neobychnyj-praznik-dlya-rebenka", destination: "/", statusCode: 301 },
      { source: "/kak-organizovat-svadebnoe-torzhestvo", destination: "/", statusCode: 301 },
      { source: "/ustraivaem-neobyknovennyj-praznik-dlya-rebenka", destination: "/", statusCode: 301 },
      { source: "/chto-glavnoe-v-v-provedenii-delovyh-meropriyatij", destination: "/", statusCode: 301 },
      { source: "/chastnye_meropriyatiya", destination: "/services/events", statusCode: 301 },
      { source: "/organizaciya-provedenie-svadeb", destination: "/services/events/dlia-svadeb", statusCode: 301 },
      { source: "/semejny-prazdnik", destination: "/services/events", statusCode: 301 },
      { source: "/provedeniye-den-rozhdeniya", destination: "/services/events/dlia-dnia-rozdeniia", statusCode: 301 },
      { source: "/malchishnik-devichnik", destination: "/services/events/dlia-svadeb", statusCode: 301 },
      { source: "/rozhdenie-rebionka", destination: "/services/events", statusCode: 301 },
      { source: "/corporate", destination: "/services/events/dlia-korporativa", statusCode: 301 },
      { source: "/den-rozhdeniya-kompanii", destination: "/services/events/dlia-korporativa", statusCode: 301 },
      { source: "/provedenie-novogo-goda", destination: "/services/events", statusCode: 301 },
      { source: "/tematicheskie-meropriyatiya", destination: "/services/events", statusCode: 301 },
      { source: "/timbilding-komandoobrazovanie", destination: "/services/events/dlia-korporativa", statusCode: 301 },
      { source: "/professionalnye-prazdniki", destination: "/services/events", statusCode: 301 },
      { source: "/massovye-meropriyatiya-narodnye-prazdniki", destination: "/services/events", statusCode: 301 },
      { source: "/prazdnik-8-marta", destination: "/services/events", statusCode: 301 },
      { source: "/korporativnyj-piknik", destination: "/services/events/dlia-korporativa", statusCode: 301 },
      { source: "/vypusknoj-vecher", destination: "/services/events", statusCode: 301 },
      { source: "/detskie_prazdniki", destination: "/services/events", statusCode: 301 },
      { source: "/koncertnye-meropriyatiya", destination: "/services/events/dlia-koncerta", statusCode: 301 },
      { source: "/biznes-meropriyatiya", destination: "/services/events/dlia-korporativa", statusCode: 301 },
      { source: "/konferencii", destination: "/services/events", statusCode: 301 },
      { source: "/prezentacii", destination: "/services/events", statusCode: 301 },
      { source: "/peregovory", destination: "/services/events", statusCode: 301 },
      { source: "/promoakcii", destination: "/services/events", statusCode: 301 },
      { source: "/vozdushnye_shary", destination: "/services/special-effects/sbros-sarov", statusCode: 301 },
      { source: "/ukrashenie-korporativov", destination: "/services/events/dlia-korporativa", statusCode: 301 },
      { source: "/yubilei-dni-rozhdeniya", destination: "/services/events", statusCode: 301 },
      { source: "/oformleniye-detskih-prazdnikov", destination: "/services/events", statusCode: 301 },
      { source: "/gorodskie-prazdniki", destination: "/services/events", statusCode: 301 },
      { source: "/vypusknye", destination: "/services/events", statusCode: 301 },
      { source: "/oformlenie-torgovyh-obektov", destination: "/services/events", statusCode: 301 },
      { source: "/vystavki", destination: "/services/events", statusCode: 301 },
      { source: "/oformleniye-23-fevralya-i-8-marta", destination: "/services/events", statusCode: 301 },
      { source: "/palitra", destination: "/services/events", statusCode: 301 },
      { source: "/pechat-logotipov-na-sharah", destination: "/", statusCode: 301 },
      { source: "/dostavka-gotovyh-kompozicij-iz-sharov", destination: "/", statusCode: 301 },
      { source: "/veduwie", destination: "/", statusCode: 301 },
      { source: "/shou-programmy", destination: "/", statusCode: 301 },
      { source: "/clown", destination: "/", statusCode: 301 },
      { source: "/fotosemka", destination: "/", statusCode: 301 },
      { source: "/videosemka", destination: "/", statusCode: 301 },
      { source: "/fejerverki-salyuty-pirotehnika", destination: "/", statusCode: 301 },
      { source: "/vyezdnoe-obsluzhivanie", destination: "/", statusCode: 301 },
      { source: "/vyezdnaya-kalyannaya", destination: "/", statusCode: 301 },
      { source: "/tancuyuwie-golovy", destination: "/", statusCode: 301 },
      { source: "/tamada", destination: "/", statusCode: 301 },
      { source: "/vostochnye_tancy", destination: "/", statusCode: 301 },
      { source: "/cygane", destination: "/", statusCode: 301 },
      { source: "/pushki-so2", destination: "/services/special-effects/kriopuska", statusCode: 301 },
      { source: "/pushki-konfetti", destination: "/services/special-effects/konfetti", statusCode: 301 },
      { source: "/serpantin", destination: "/services/special-effects/serpantin", statusCode: 301 },
      { source: "/prokat-stolbikov-s-kanatami-krasnoj-dorozhki", destination: "/services/special-effects/stolbiki-noznicy", statusCode: 301 },
      { source: "/lenty-pocheta-lenty-vypusknikov", destination: "/services/special-effects/stolbiki-noznicy", statusCode: 301 },
      { source: "/pnevmohlopushki-nebesnye-fonariki", destination: "/", statusCode: 301 },
      { source: "/ballony", destination: "/services/special-effects/sbros-sarov", statusCode: 301 },
      { source: "/gelievye-shary", destination: "/services/special-effects/sbros-sarov", statusCode: 301 },
      { source: "/novyj-god", destination: "/", statusCode: 301 },
      { source: "/novogodnee-oformlenie-novogodnie-ukrasheniya", destination: "/", statusCode: 301 },
      { source: "/iskusstvennye-eli", destination: "/", statusCode: 301 },
      { source: "/girlyandy-elektricheskie", destination: "/", statusCode: 301 },
      { source: "/organizaciya-provedenie-svadeb", destination: "/services/events/dlia-svadeb", statusCode: 301 },
      { source: "/vypusknoj-vecher", destination: "/", statusCode: 301 },
      { source: "/chastnye_meropriyatiya", destination: "/", statusCode: 301 },
      { source: "/corporate", destination: "/services/events/dlia-korporativa", statusCode: 301 },
      { source: "/vypusknoj-vecher", destination: "/", statusCode: 301 },
      { source: "/detskie_prazdniki", destination: "/", statusCode: 301 },
      { source: "/koncertnye-meropriyatiya", destination: "/", statusCode: 301 },
      { source: "/biznes-meropriyatiya", destination: "/", statusCode: 301 },
    ]
  },
  async rewrites() {
    return [
      { source: "/robots.txt", destination: "/api/robots" },
      { source: "/sitemap.xml", destination: "/api/sitemap.xml" },
      { source: "/feed.xml", destination: "/api/feed" },
    ];
  },


};

export default nextConfig;
